
- name: Deploy Docker Compose Setup
  hosts: servers
  become: no  
  tasks:
  
    - name: Clone my repoo
      git:
        repo: git@github.com:Katy0903/acit3855_lab9.git
        dest: /home/katy/acit3855_lab9/demo
        version: main
        accept_hostkey: yes
        key_file: ~/.ssh/bcitkey
        force: true

    - name: Copy all files from prod to test
      synchronize:
        src: ../config/prod/
        dest: /home/katy/acit3855_lab9/demo/config/test/
        mode: push 
        recursive: yes       
        
    # - name: Copy file 
    #   copy:
    #     src: ../config/prod/storage/app_conf.yml
    #     dest: /home/katy/acit3855_lab9/demo/config/test/storage/app_conf.yml
    #     owner: katy
    #     group: katy
    #     mode: '0644'
    #     force: true

    - name: Run Docker Compose up -d --build
      ansible.builtin.shell: |
        cd /home/katy/acit3855_lab9/demo
        chown -R katy:katy ./data
        chown -R katy:katy ./logs
        docker compose up -d --build
      args:
        executable: /bin/bash


