
- name: Deploy Docker Compose Setup
  hosts: servers
  become: no  
  tasks:
  
    - name: Clone my repo
      git:
        repo: git@github.com:Katy0903/acit3855_lab9.git
        dest: /home/katy/demo
        version: main
        accept_hostkey: yes
        key_file: ~/.ssh/bcitkey

        
    # - name: Run Docker Compose up -d --build
    #   ansible.builtin.shell: |
    #     cd /home/katy/demo/test
    #     docker compose up -d --build
    #   args:
    #     executable: /bin/bash
