
- name: Deploy Docker Compose Setup
  hosts: servers
  become: no  
  tasks:
  
    - name: Clone my repo
      git:
        repo: git@github.com:Katy0903/acit3855_lab9.git
        dest: /home/katy/acit3855_lab9/demo
        version: main
        accept_hostkey: yes
        key_file: ~/.ssh/bcitkey
        force: true


    - name: Copy file 
      copy:
        src: /config/prod/
        dest: /home/katy/acit3855_lab9/demo/test
        remote_src: yes
        owner: katy
        group: katy
        mode: '0644'

    - name: Run Docker Compose up -d --build
      ansible.builtin.shell: |
        cd /home/katy/acit3855_lab9/demo
        mkdir data
        mkdir logs
        chown -R katy:katy ./data
        chown -R katy:katy ./logs
        docker compose up -d --build
      args:
        executable: /bin/bash


